name: Bug Report
description: Please do not use bug reports for support issues or feature requests.
title: '[Bug]: '
type: 'Bug'
assignees: 'bullmoose20'

body:
  - type: markdown
    attributes:
      value: >
        **THIS IS NOT THE PLACE TO ASK FOR SUPPORT OR FEATURE REQUESTS!**
        Please use [Kometa Discord](https://kometa.wiki/en/latest/discord/) and post your question under the ` kometa-help` channel for support issues.
  - type: input
    id: version
    attributes:
      label: Version Number
      description: Can be found in the VERSION file
      placeholder: eg. 1.0.1
    validations:
      required: false
  - type: dropdown
    id: branch
    attributes:
      label: What branch are you on?
      options:
        - master
        - develop
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: input
    id: logs
    attributes:
      label: Logs
      description: >
        Please share the relevant log file with the error on [Gist](https://gist.github.com).
      placeholder: "https://gist.github.com"